version: "3.8"

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zeldaspeedruns
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass zeldaspeedruns
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
