version: "3.8"

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zeldaspeedruns
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass zeldaspeedruns
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  keycloak:
    image: jboss/keycloak
    restart: always
    depends_on:
      - keycloak-db
      - mailhog
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: zsr
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
  keycloak-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"